import {
  AddWorksheetMergeAllCommand,
  AddWorksheetMergeCommand,
  AddWorksheetMergeHorizontalCommand,
  AddWorksheetMergeVerticalCommand,
  AppendRowCommand,
  CancelFrozenCommand,
  ClearSelectionFormatCommand,
  CopySheetCommand,
  DeleteRangeMoveLeftCommand,
  DeleteRangeMoveUpCommand,
  DeltaColumnWidthCommand,
  DeltaRowHeightCommand,
  InsertColAfterCommand,
  InsertColBeforeCommand,
  InsertColByRangeCommand,
  InsertColCommand,
  InsertMultiColsLeftCommand,
  InsertMultiColsRightCommand,
  InsertMultiRowsAboveCommand,
  InsertMultiRowsAfterCommand,
  InsertRangeMoveDownCommand,
  InsertRangeMoveRightCommand,
  InsertRowAfterCommand,
  InsertRowBeforeCommand,
  InsertRowByRangeCommand,
  InsertRowCommand,
  InsertSheetCommand,
  MoveColsCommand,
  MoveRowsCommand,
  RemoveColByRangeCommand,
  RemoveColCommand,
  RemoveRowByRangeCommand,
  RemoveRowCommand,
  RemoveSheetCommand,
  RemoveWorksheetMergeCommand,
  ResetBackgroundColorCommand,
  ResetTextColorCommand,
  SetBackgroundColorCommand,
  SetBoldCommand,
  SetBorderBasicCommand,
  SetBorderColorCommand,
  SetBorderCommand,
  SetBorderPositionCommand,
  SetBorderStyleCommand,
  SetColDataCommand,
  SetColHiddenCommand,
  SetColWidthCommand,
  SetFontFamilyCommand,
  SetFontSizeCommand,
  SetFrozenCommand,
  SetGridlinesColorCommand,
  SetHorizontalTextAlignCommand,
  SetItalicCommand,
  SetOverlineCommand,
  SetRowDataCommand,
  SetRowHeightCommand,
  SetRowHiddenCommand,
  SetSelectedColsVisibleCommand,
  SetSelectedRowsVisibleCommand,
  SetSpecificColsVisibleCommand,
  SetSpecificRowsVisibleCommand,
  SetStrikeThroughCommand,
  SetStyleCommand,
  SetTabColorCommand,
  SetTextColorCommand,
  SetTextRotationCommand,
  SetTextWrapCommand,
  SetUnderlineCommand,
  SetVerticalTextAlignCommand,
  SetWorksheetColumnCountCommand,
  SetWorksheetDefaultStyleCommand,
  SetWorksheetHideCommand,
  SetWorksheetNameCommand,
  SetWorksheetOrderCommand,
  SetWorksheetRowCountCommand,
  SetWorksheetRowIsAutoHeightCommand,
  SetWorksheetShowCommand,
  ToggleGridlinesCommand,
} from "@univerjs/sheets";

export const POLYSHEET_UNIVER_UI_POLICY = {
  contextMenu: false,
  toolbar: false,
  footer: {
    sheetBar: false,
    statisticBar: true,
    menus: false,
  },
} as const;

const BLOCKED_UNMANAGED_COMMAND_IDS = new Set(
  [
    AddWorksheetMergeAllCommand,
    AddWorksheetMergeCommand,
    AddWorksheetMergeHorizontalCommand,
    AddWorksheetMergeVerticalCommand,
    AppendRowCommand,
    CancelFrozenCommand,
    ClearSelectionFormatCommand,
    CopySheetCommand,
    DeleteRangeMoveLeftCommand,
    DeleteRangeMoveUpCommand,
    DeltaColumnWidthCommand,
    DeltaRowHeightCommand,
    InsertColAfterCommand,
    InsertColBeforeCommand,
    InsertColByRangeCommand,
    InsertColCommand,
    InsertMultiColsLeftCommand,
    InsertMultiColsRightCommand,
    InsertMultiRowsAboveCommand,
    InsertMultiRowsAfterCommand,
    InsertRangeMoveDownCommand,
    InsertRangeMoveRightCommand,
    InsertRowAfterCommand,
    InsertRowBeforeCommand,
    InsertRowByRangeCommand,
    InsertRowCommand,
    InsertSheetCommand,
    MoveColsCommand,
    MoveRowsCommand,
    RemoveColByRangeCommand,
    RemoveColCommand,
    RemoveRowByRangeCommand,
    RemoveRowCommand,
    RemoveSheetCommand,
    RemoveWorksheetMergeCommand,
    ResetBackgroundColorCommand,
    ResetTextColorCommand,
    SetBackgroundColorCommand,
    SetBoldCommand,
    SetBorderBasicCommand,
    SetBorderColorCommand,
    SetBorderCommand,
    SetBorderPositionCommand,
    SetBorderStyleCommand,
    SetColDataCommand,
    SetColHiddenCommand,
    SetColWidthCommand,
    SetFontFamilyCommand,
    SetFontSizeCommand,
    SetFrozenCommand,
    SetGridlinesColorCommand,
    SetHorizontalTextAlignCommand,
    SetItalicCommand,
    SetOverlineCommand,
    SetRowDataCommand,
    SetRowHeightCommand,
    SetRowHiddenCommand,
    SetSelectedColsVisibleCommand,
    SetSelectedRowsVisibleCommand,
    SetSpecificColsVisibleCommand,
    SetSpecificRowsVisibleCommand,
    SetStrikeThroughCommand,
    SetStyleCommand,
    SetTabColorCommand,
    SetTextColorCommand,
    SetTextRotationCommand,
    SetTextWrapCommand,
    SetUnderlineCommand,
    SetVerticalTextAlignCommand,
    SetWorksheetColumnCountCommand,
    SetWorksheetDefaultStyleCommand,
    SetWorksheetHideCommand,
    SetWorksheetNameCommand,
    SetWorksheetOrderCommand,
    SetWorksheetRowCountCommand,
    SetWorksheetRowIsAutoHeightCommand,
    SetWorksheetShowCommand,
    ToggleGridlinesCommand,
  ].map((command) => command.id),
);

[
  "sheet.command.numfmt.add.decimal.command",
  "sheet.command.numfmt.set.currency",
  "sheet.command.numfmt.set.numfmt",
  "sheet.command.numfmt.set.percent",
  "sheet.command.numfmt.subtract.decimal.command",
  "sheet.command.set-col-auto-width",
  "sheet.command.set-col-is-auto-width",
  "sheet.command.set-col-header-height",
  "sheet.command.set-col-frozen",
  "sheet.command.set-first-column-frozen",
  "sheet.command.set-first-row-frozen",
  "sheet.command.set-row-frozen",
  "sheet.command.set-row-header-width",
].forEach((commandId) => BLOCKED_UNMANAGED_COMMAND_IDS.add(commandId));

export function isBlockedUnmanagedCommand(commandId: string) {
  return BLOCKED_UNMANAGED_COMMAND_IDS.has(commandId);
}

export type SyncSheet = {
  id: string;
  kind: "data" | "calculation";
};

export function collectChangedCalculationUpdates<
  TSheet extends SyncSheet,
  TDocument,
>(
  sheets: readonly TSheet[],
  currentBySheet: ReadonlyMap<string, TDocument>,
  readDocument: (sheet: TSheet) => TDocument,
) {
  return sheets.flatMap((sheet) => {
    if (sheet.kind !== "calculation") return [];
    const current = currentBySheet.get(sheet.id);
    const document = readDocument(sheet);
    return current && JSON.stringify(current) === JSON.stringify(document)
      ? []
      : [{ sheet, document }];
  });
}
