#!/usr/bin/env python3
"""Validate generated PolyGen MySQL/MariaDB DDL without requiring a server."""

from __future__ import annotations

import re
import sys
from pathlib import Path


TABLE_RE = re.compile(
    r"CREATE TABLE IF NOT EXISTS `(?P<name>[A-Za-z_][A-Za-z0-9_]*)` \(\n"
    r"(?P<body>.*?)\n\) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
    re.DOTALL,
)
INDEX_RE = re.compile(
    r"CREATE (?P<unique>UNIQUE )?INDEX `(?P<name>[A-Za-z_][A-Za-z0-9_]*)` "
    r"ON `(?P<table>[A-Za-z_][A-Za-z0-9_]*)` \((?P<fields>`[^`]+`(?:, `[^`]+`)*)\);"
)
COLUMN_RE = re.compile(
    r"^`(?P<name>[A-Za-z_][A-Za-z0-9_]*)` "
    r"(?P<type>(?:TINYINT|SMALLINT|INT|BIGINT)(?: UNSIGNED)?|FLOAT|DOUBLE|BOOLEAN|BLOB|TIMESTAMP|VARCHAR\(\d+\)|TEXT|LONGTEXT)"
    r"(?P<attrs> .*)?$"
)
PRIMARY_KEY_RE = re.compile(r"^PRIMARY KEY \((?P<fields>`[^`]+`(?:, `[^`]+`)*)\)$")
UNIQUE_RE = re.compile(r"^UNIQUE \((?P<field>`[^`]+`)\)$")
FOREIGN_KEY_RE = re.compile(
    r"^FOREIGN KEY \((?P<field>`[^`]+`)\) "
    r"REFERENCES `(?P<table>[A-Za-z_][A-Za-z0-9_]*)` \((?P<ref_field>`[^`]+`)\)$"
)

METADATA_TABLES = {"_polygen_schema", "_polygen_migrations"}


def fail(path: Path, message: str) -> None:
    raise ValueError(f"{path}: {message}")


def require(condition: bool, path: Path, message: str) -> None:
    if not condition:
        fail(path, message)


def split_clause_fields(fields: str) -> list[str]:
    return [field.strip(" `") for field in fields.split(",")]


def validate_table_body(path: Path, table_name: str, body: str) -> set[str]:
    columns: set[str] = set()
    for raw_line in body.split(",\n"):
        line = raw_line.strip()
        if not line:
            continue

        column = COLUMN_RE.match(line)
        if column:
            columns.add(column.group("name"))
            continue

        primary_key = PRIMARY_KEY_RE.match(line)
        if primary_key:
            for field in split_clause_fields(primary_key.group("fields")):
                require(field in columns, path, f"{table_name}: primary key references unknown column {field!r}")
            continue

        unique = UNIQUE_RE.match(line)
        if unique:
            field = unique.group("field").strip("`")
            require(field in columns, path, f"{table_name}: unique references unknown column {field!r}")
            continue

        foreign_key = FOREIGN_KEY_RE.match(line)
        if foreign_key:
            field = foreign_key.group("field").strip("`")
            require(field in columns, path, f"{table_name}: foreign key references unknown column {field!r}")
            continue

        fail(path, f"{table_name}: unrecognized table clause {line!r}")

    require(columns, path, f"{table_name}: table must contain at least one column")
    return columns


def validate_mysql(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    require("-- Generated by PolyGen (MySQL/MariaDB)" in text, path, "missing generator header")
    require("ON DUPLICATE KEY UPDATE" in text, path, "missing metadata upsert")
    require("DEFAULT CHARSET=utf8mb4" in text, path, "missing utf8mb4 table options")

    table_matches = list(TABLE_RE.finditer(text))
    require(table_matches, path, "no CREATE TABLE statements found")

    table_names = [match.group("name") for match in table_matches]
    require(len(table_names) == len(set(table_names)), path, "duplicate CREATE TABLE names")
    require(METADATA_TABLES.issubset(table_names), path, "missing metadata tables")

    user_tables = [name for name in table_names if name not in METADATA_TABLES]
    is_complex_schema = "08_complex_schema" in path.parts
    if user_tables:
        require("-- No MySQL datasource tables found." not in text, path, "placeholder emitted despite user tables")
    else:
        require(not is_complex_schema, path, "complex schema generated no user tables")
        require("-- No MySQL datasource tables found." in text, path, "missing no-table placeholder")

    columns_by_table: dict[str, set[str]] = {}
    for match in table_matches:
        table_name = match.group("name")
        columns_by_table[table_name] = validate_table_body(path, table_name, match.group("body"))

    for foreign_key in FOREIGN_KEY_RE.finditer(text):
        ref_table = foreign_key.group("table")
        ref_field = foreign_key.group("ref_field").strip("`")
        require(ref_table in columns_by_table, path, f"foreign key references unknown table {ref_table!r}")
        require(ref_field in columns_by_table[ref_table], path, f"foreign key references unknown column {ref_table}.{ref_field}")

    seen_indexes: set[str] = set()
    for index in INDEX_RE.finditer(text):
        index_name = index.group("name")
        table_name = index.group("table")
        require(index_name not in seen_indexes, path, f"duplicate index name {index_name!r}")
        require(table_name in columns_by_table, path, f"index {index_name!r} references unknown table {table_name!r}")
        for field in split_clause_fields(index.group("fields")):
            require(field in columns_by_table[table_name], path, f"index {index_name!r} references unknown column {field!r}")
        seen_indexes.add(index_name)

    if is_complex_schema:
        require("FOREIGN KEY" in text, path, "complex schema should include foreign keys")
        require(seen_indexes, path, "complex schema should include indexes")


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: validate_mysql.py <schema.sql>", file=sys.stderr)
        return 2

    validate_mysql(Path(argv[1]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
