#!/usr/bin/env python3
"""Validate generated PolyGen SQLite DDL using Python's built-in sqlite3."""

from __future__ import annotations

import re
import sqlite3
import sys
from pathlib import Path


TABLE_RE = re.compile(r"CREATE TABLE IF NOT EXISTS (?P<name>[A-Za-z_][A-Za-z0-9_]*) \(", re.MULTILINE)
INDEX_RE = re.compile(
    r"CREATE (?P<unique>UNIQUE )?INDEX IF NOT EXISTS (?P<name>[A-Za-z_][A-Za-z0-9_]*) "
    r"ON (?P<table>[A-Za-z_][A-Za-z0-9_]*) \((?P<fields>[A-Za-z_][A-Za-z0-9_]*(?:, [A-Za-z_][A-Za-z0-9_]*)*)\);"
)
FOREIGN_KEY_RE = re.compile(
    r"FOREIGN KEY \((?P<field>[A-Za-z_][A-Za-z0-9_]*)\) "
    r"REFERENCES (?P<table>[A-Za-z_][A-Za-z0-9_]*)\((?P<ref_field>[A-Za-z_][A-Za-z0-9_]*)\)"
)
TRIGGER_RE = re.compile(r"CREATE TRIGGER IF NOT EXISTS (?P<name>[A-Za-z_][A-Za-z0-9_]*)")

METADATA_TABLES = {"_polygen_schema", "_polygen_migrations"}


def fail(path: Path, message: str) -> None:
    raise ValueError(f"{path}: {message}")


def require(condition: bool, path: Path, message: str) -> None:
    if not condition:
        fail(path, message)


def execute_sql(path: Path, text: str) -> sqlite3.Connection:
    conn = sqlite3.connect(":memory:")
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        conn.executescript(text)
    except sqlite3.Error as exc:
        fail(path, f"SQLite executescript failed: {exc}")
    return conn


def table_columns(conn: sqlite3.Connection, table_name: str) -> set[str]:
    return {row[1] for row in conn.execute(f'PRAGMA table_info("{table_name}")')}


def validate_sqlite(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    require("-- Generated by PolyGen (SQLite)" in text, path, "missing generator header")
    require("PRAGMA foreign_keys = ON;" in text, path, "missing foreign key pragma")
    require("ON CONFLICT(id) DO UPDATE SET" in text, path, "missing metadata upsert")

    conn = execute_sql(path, text)

    created_tables = {
        row[0]
        for row in conn.execute(
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'"
        )
    }
    require(METADATA_TABLES.issubset(created_tables), path, "missing metadata tables")

    user_tables = created_tables - METADATA_TABLES
    require(user_tables, path, "missing user tables")

    declared_tables = {match.group("name") for match in TABLE_RE.finditer(text)}
    require(created_tables.issubset(declared_tables), path, "sqlite_master contains undeclared tables")

    columns_by_table = {table: table_columns(conn, table) for table in created_tables}
    for table, columns in columns_by_table.items():
        require(columns, path, f"{table}: table must contain at least one column")

    for fk in FOREIGN_KEY_RE.finditer(text):
        ref_table = fk.group("table")
        ref_field = fk.group("ref_field")
        require(ref_table in columns_by_table, path, f"foreign key references unknown table {ref_table!r}")
        require(ref_field in columns_by_table[ref_table], path, f"foreign key references unknown column {ref_table}.{ref_field}")

    seen_indexes: set[str] = set()
    for index in INDEX_RE.finditer(text):
        index_name = index.group("name")
        table_name = index.group("table")
        require(index_name not in seen_indexes, path, f"duplicate index name {index_name!r}")
        require(table_name in columns_by_table, path, f"index {index_name!r} references unknown table {table_name!r}")
        for field in index.group("fields").split(", "):
            require(field in columns_by_table[table_name], path, f"index {index_name!r} references unknown column {field!r}")
        seen_indexes.add(index_name)

    sqlite_indexes = {
        row[0]
        for row in conn.execute(
            "SELECT name FROM sqlite_master WHERE type = 'index' AND name NOT LIKE 'sqlite_%'"
        )
    }
    require(seen_indexes.issubset(sqlite_indexes), path, "declared indexes were not created")

    for trigger in TRIGGER_RE.finditer(text):
        trigger_name = trigger.group("name")
        exists = conn.execute(
            "SELECT 1 FROM sqlite_master WHERE type = 'trigger' AND name = ?",
            (trigger_name,),
        ).fetchone()
        require(exists is not None, path, f"trigger {trigger_name!r} was not created")

    if "08_complex_schema" in path.parts:
        require("game_character_Player" in created_tables, path, "complex schema missing nested Player table")
        require("game_item_Item" in created_tables, path, "complex schema missing nested Item table")
        require("game_inventory_InventorySlot" in created_tables, path, "complex schema missing nested InventorySlot table")
        require("game_common_Element" in created_tables, path, "complex schema missing nested enum table")
        require("game_common_Vec3" not in created_tables, path, "embed Vec3 should not be emitted as a table")
        require("FOREIGN KEY" in text, path, "complex schema should include foreign keys")
        require(seen_indexes, path, "complex schema should include indexes")

    if "09_sqlite" in path.parts:
        require({"test_sqlite_User", "test_sqlite_Post", "test_sqlite_Comment", "test_sqlite_audit_LoginEvent"}.issubset(created_tables), path, "sqlite fixture missing expected tables")
        require("FOREIGN KEY (user_id) REFERENCES test_sqlite_User(id)" in text, path, "sqlite fixture missing user FK")


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: validate_sqlite.py <schema.sql>", file=sys.stderr)
        return 2

    validate_sqlite(Path(argv[1]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
