//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace game.common {
public enum Element
{
    PHYSICAL,
    FIRE,
    ICE,
    LIGHTNING,
}
public partial struct Position
{
    public float X { get; set; }

    
    public float Y { get; set; }
}
public partial struct StatBlock
{
    public uint Health { get; set; }

    
    public uint Mana { get; set; }

    
    public uint Attack { get; set; }

    
    public uint Defense { get; set; }
}


}
