//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace game.item {
public enum ItemType
{
    WEAPON,
    ARMOR,
    POTION,
    MATERIAL,
}
public partial class Item
{
    public uint Id { get; set; }

    
    public string Name { get; set; }

    
    public ItemType ItemType { get; set; }

    
    public string Description { get; set; }
}


}


namespace game.character {
public partial class Player
{
    public uint Id { get; set; }

    
    public string Name { get; set; }

    
    public ushort Level { get; set; }

    
    public game.common.StatBlock Stats { get; set; }
}
public partial class Monster
{
    public class DropItems
    {
        public uint ItemId { get; set; }
        public float DropChance { get; set; }
    }
    public uint Id { get; set; }

    
    public string Name { get; set; }

    
    public game.common.StatBlock Stats { get; set; }

    
    public game.common.Position SpawnPoint { get; set; }

    
    public System.Collections.Generic.List<game.common.Position> PatrolPoints { get; set; }

    
    public System.Collections.Generic.List<DropItems> DropItems { get; set; }
}


}


namespace game.junction {
public partial class PlayerSkill
{
    public uint PlayerId { get; set; }

    
    public uint SkillId { get; set; }

    
    public ushort SkillLevel { get; set; }
}
public partial class InventoryItem
{
    public uint Id { get; set; }

    
    public uint PlayerId { get; set; }

    
    public uint ItemId { get; set; }

    
    public uint Quantity { get; set; }
}


}
