#!/usr/bin/env python3
"""Validate generated PolyGen PostgreSQL DDL without requiring a server."""

from __future__ import annotations

import re
import sys
from pathlib import Path


IDENT = r'"[A-Za-z_][A-Za-z0-9_]*"'
TABLE_RE = re.compile(
    rf"CREATE TABLE IF NOT EXISTS (?P<quoted>{IDENT}) \(\n(?P<body>.*?)\n\);",
    re.DOTALL,
)
INDEX_RE = re.compile(
    rf"CREATE (?P<unique>UNIQUE )?INDEX IF NOT EXISTS (?P<name>{IDENT}) "
    rf"ON (?P<table>{IDENT}) \((?P<fields>{IDENT}(?:, {IDENT})*)\);"
)
COLUMN_RE = re.compile(
    rf"^(?P<name>{IDENT}) "
    r"(?P<type>SMALLINT|INTEGER|BIGINT|REAL|DOUBLE PRECISION|BOOLEAN|BYTEA|TIMESTAMPTZ|VARCHAR\(\d+\)|TEXT|JSONB|BIGSERIAL)"
    r"(?P<attrs> .*)?$"
)
PRIMARY_KEY_RE = re.compile(rf"^PRIMARY KEY \((?P<fields>{IDENT}(?:, {IDENT})*)\)$")
UNIQUE_RE = re.compile(rf"^UNIQUE \((?P<field>{IDENT})\)$")
FOREIGN_KEY_RE = re.compile(
    rf"^FOREIGN KEY \((?P<field>{IDENT})\) "
    rf"REFERENCES (?P<table>{IDENT}) \((?P<ref_field>{IDENT})\)$"
)
TRIGGER_RE = re.compile(
    rf"CREATE TRIGGER (?P<name>{IDENT})\n"
    rf"BEFORE UPDATE ON (?P<table>{IDENT})\n"
    r"FOR EACH ROW\n"
    rf"EXECUTE FUNCTION (?P<function>{IDENT})\(\);"
)

METADATA_TABLES = {"_polygen_schema", "_polygen_migrations"}


def fail(path: Path, message: str) -> None:
    raise ValueError(f"{path}: {message}")


def require(condition: bool, path: Path, message: str) -> None:
    if not condition:
        fail(path, message)


def unquote(value: str) -> str:
    return value.strip('"')


def split_clause_fields(fields: str) -> list[str]:
    return [unquote(field.strip()) for field in fields.split(",")]


def validate_table_body(path: Path, table_name: str, body: str) -> set[str]:
    columns: set[str] = set()

    for raw_line in body.split(",\n"):
        line = raw_line.strip()
        if not line:
            continue

        column = COLUMN_RE.match(line)
        if column:
            columns.add(unquote(column.group("name")))
            continue

        primary_key = PRIMARY_KEY_RE.match(line)
        if primary_key:
            for field in split_clause_fields(primary_key.group("fields")):
                require(field in columns, path, f"{table_name}: primary key references unknown column {field!r}")
            continue

        unique = UNIQUE_RE.match(line)
        if unique:
            field = unquote(unique.group("field"))
            require(field in columns, path, f"{table_name}: unique references unknown column {field!r}")
            continue

        foreign_key = FOREIGN_KEY_RE.match(line)
        if foreign_key:
            field = unquote(foreign_key.group("field"))
            require(field in columns, path, f"{table_name}: foreign key references unknown column {field!r}")
            continue

        fail(path, f"{table_name}: unrecognized table clause {line!r}")

    require(columns, path, f"{table_name}: table must contain at least one column")
    return columns


def validate_postgresql(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    require("-- Generated by PolyGen (PostgreSQL)" in text, path, "missing generator header")
    require("ON CONFLICT (\"id\") DO UPDATE SET" in text, path, "missing metadata upsert")
    require("\"schema_json\" JSONB" in text, path, "missing JSONB metadata column")

    table_matches = list(TABLE_RE.finditer(text))
    require(table_matches, path, "no CREATE TABLE statements found")

    table_names = [unquote(match.group("quoted")) for match in table_matches]
    require(len(table_names) == len(set(table_names)), path, "duplicate CREATE TABLE names")
    require(METADATA_TABLES.issubset(table_names), path, "missing metadata tables")

    user_tables = [name for name in table_names if name not in METADATA_TABLES]
    is_complex_schema = "08_complex_schema" in path.parts
    if user_tables:
        require("-- No PostgreSQL datasource tables found." not in text, path, "placeholder emitted despite user tables")
    else:
        require(not is_complex_schema, path, "complex schema generated no user tables")
        require("-- No PostgreSQL datasource tables found." in text, path, "missing no-table placeholder")

    columns_by_table: dict[str, set[str]] = {}
    for match in table_matches:
        table_name = unquote(match.group("quoted"))
        columns_by_table[table_name] = validate_table_body(path, table_name, match.group("body"))

    for foreign_key in FOREIGN_KEY_RE.finditer(text):
        ref_table = unquote(foreign_key.group("table"))
        ref_field = unquote(foreign_key.group("ref_field"))
        require(ref_table in columns_by_table, path, f"foreign key references unknown table {ref_table!r}")
        require(ref_field in columns_by_table[ref_table], path, f"foreign key references unknown column {ref_table}.{ref_field}")

    seen_indexes: set[str] = set()
    for index in INDEX_RE.finditer(text):
        index_name = unquote(index.group("name"))
        table_name = unquote(index.group("table"))
        require(index_name not in seen_indexes, path, f"duplicate index name {index_name!r}")
        require(table_name in columns_by_table, path, f"index {index_name!r} references unknown table {table_name!r}")
        for field in split_clause_fields(index.group("fields")):
            require(field in columns_by_table[table_name], path, f"index {index_name!r} references unknown column {field!r}")
        seen_indexes.add(index_name)

    for trigger in TRIGGER_RE.finditer(text):
        table_name = unquote(trigger.group("table"))
        require(table_name in columns_by_table, path, f"trigger references unknown table {table_name!r}")

    if is_complex_schema:
        require("FOREIGN KEY" in text, path, "complex schema should include foreign keys")
        require(seen_indexes, path, "complex schema should include indexes")


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: validate_postgresql.py <schema.sql>", file=sys.stderr)
        return 2

    validate_postgresql(Path(argv[1]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
